# Generated by Django 3.2.4 on 2021-06-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='description',
            field=models.TextField(default='add'),
        ),
    ]
